# prometheus-rules.yml

groups:
  - name: jaeger-spanmetrics-alias
    rules:
      - record: calls_total
        expr: traces_span_metrics_calls_total
      - record: duration_milliseconds_sum
        expr: traces_span_metrics_duration_milliseconds_sum
      - record: duration_milliseconds_count
        expr: traces_span_metrics_duration_milliseconds_count
      - record: duration_milliseconds_bucket
        expr: traces_span_metrics_duration_milliseconds_bucket
